name: Build and Deploy to Azure Contanirize Apps 
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: creditscoutregistry39.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: creditscoutregistry39.azurecr.io/credit-scout-api:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          image: creditscoutregistry39.azurecr.io/credit-scout-api:${{ github.sha }}
          container-app-name: credit-scout-app
          resource-group: credit-scout-rg